### ISSUE TITLE
Create a README.md

### ISSUE THREAD

**Issue by Luccasoli** [Luccasoli/tasks-app#1]
ENGLISH:
Display information about the project for easier understanding.
Ex.:
- Which is?
- How to test?
- Preview
- License

PORTUGUESE:
Exibir informações sobre o projeto para facilitar a compreensão.
Ex.:
- O que é?
- Como testar?
- Prévias
- Licença

**Comment by GussSoares** [comment]
abri um PR lá

**Comment by Luccasoli** [comment]
solved by #5
